version: "3"

networks:
  proxy:
    name: proxy

services:
  traefik:
    image: traefik:latest
    restart: always

    # handled through traefik.yml
    # command:
    #   - "--log.level=DEBUG"
    #   - "--providers.docker"
    #   - "--providers.docker.exposedByDefault=false"
    #   - "--providers.docker.network=proxy"
    #   - "--entrypoints.http.address=:80"
    #   - "--entrypoints.http.http.redirections.entrypoint.to=https"
    #   - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
    #   - "--entrypoints.https.address=:443"
    #   - "--entrypoints.https.http.tls.certResolver=le"
    #   - "--certificatesresolvers.le.acme.tlschallenge=true"
    #   - "--certificatesresolvers.le.acme.email=it@queerreferat-aachen.de"
    #   - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    #   - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "${DOCKER_PATH}:/var/run/docker.sock:ro"
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ../nextcloud/nextcloud.yml:/etc/traefik/providers/nextcloud.yml
    networks:
      - proxy
    env_file:
      - .env
