version: "3"

volumes:
  letsencrypt:

networks:
  proxy:
    name: proxy

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`queerreferat.ac`) && PathPrefix(`/api`, `/dashboard`)"
      - "traefik.http.routers.dashboard.priority=10"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=authentik"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik-server-1:9000/outpost.goauthentik.io/auth/traefik"
      # this shows up in all the examples, but doesn't seem to be needed?
      # - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      # see https://goauthentik.io/docs/providers/proxy/server_traefik for possible headers
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username"

