version: "3"

volumes:
  letsencrypt:

networks:
  proxy:
    name: proxy

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy
